# THIS FILE IS EXCLUSIVELY MAINTAINED by the project aedev.project_tpls v0.3.96
""" setup of aedev namespace-root: aedev namespace root, providing setup, development and documentation tools/templates for Python projects.. """
import pathlib
import sys
from typing import Any
import setuptools


print("SetUp " + __name__ + ": " + sys.executable + str(sys.argv) + f" {sys.path=}")

setup_kwargs: dict[str, Any] = {
    'author': 'AndiEcker',
    'author_email': 'aecker2@gmail.com',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.12',
        'Topic :: Software Development',
        'Typing :: Typed',
    ],
    'description': 'aedev namespace-root: aedev namespace root, providing setup, development and documentation tools/templates for Python projects.',
    'extras_require': {
        'dev': [
            'aedev_base==0.3.10',
            'aedev_commands==0.3.16',
            'aedev_project_vars==0.3.22',
            'aedev_project_manager==0.3.33',
            'aedev_project_tpls==0.3.96',
            'aedev_namespace_root_tpls==0.3.33',
            'ae_app_log==0.3.3',
            'ae_base==0.3.91',
            'ae_console==0.3.97',
            'ae_core==0.3.88',
            'ae_dynamicod==0.3.16',
            'ae_files==0.3.31',
            'ae_literal==0.3.36',
            'ae_managed_files==0.3.7',
            'ae_paths==0.3.46',
            'ae_pythonanywhere==0.3.9',
            'ae_shell==0.3.15',
            'ae_system==0.3.12',
            'ae_updater==0.3.20',
            'aedev_app_tpls==0.3.22',
            'alabaster==1.0.0',
            'anybadge==1.16.0',
            'argcomplete==3.6.3',
            'ast_serialize==0.6.0',
            'astroid==4.0.4',
            'babel==2.18.0',
            'certifi==2026.6.17',
            'cffi==2.0.0',
            'charset-normalizer==3.4.7',
            'click==8.4.1',
            'coverage==7.15.3',
            'cryptography==49.0.0',
            'dill==0.4.1',
            'docutils==0.22.4',
            'filelock==3.30.0',
            'flake8==7.3.0',
            'idna==3.18',
            'imagesize==2.0.0',
            'iniconfig==2.3.0',
            'isort==8.0.1',
            'Jinja2==3.1.6',
            'librt==0.13.0',
            'MarkupSafe==3.0.3',
            'mccabe==0.7.0',
            'mypy==2.3.0',
            'mypy_extensions==1.1.0',
            'packaging==26.3',
            'pathspec==1.1.1',
            'pillow==12.3.0',
            'pipx==1.16.6',
            'platformdirs==4.10.0',
            'pluggy==1.6.0',
            'pyasn1==0.6.4',
            'pyasn1_modules==0.4.2',
            'pycodestyle==2.14.0',
            'pycparser==3.0',
            'pyflakes==3.4.0',
            'PyGithub==2.9.1',
            'Pygments==2.20.0',
            'pyjnius==1.7.0',
            'PyJWT==2.13.0',
            'pylint==4.0.6',
            'PyNaCl==1.6.2',
            'pytest==9.1.1',
            'pytest-cov==7.1.0',
            'python-gitlab==8.5.0',
            'requests==2.34.2',
            'requests-toolbelt==1.0.0',
            'roman-numerals==4.1.0',
            'setuptools==83.0.0',
            'snowballstemmer==3.1.1',
            'Sphinx==9.1.0',
            'sphinx-autodoc-typehints==3.13.2',
            'sphinx-paramlinks==0.6.0',
            'sphinx_rtd_theme==3.1.0',
            'sphinxcontrib-applehelp==2.0.0',
            'sphinxcontrib-devhelp==2.0.0',
            'sphinxcontrib-htmlhelp==2.1.0',
            'sphinxcontrib-jquery==4.1',
            'sphinxcontrib-jsmath==1.0.1',
            'sphinxcontrib-qthelp==2.0.0',
            'sphinxcontrib-serializinghtml==2.0.0',
            'tomlkit==0.15.0',
            'types-Pillow==10.2.0.20240822',
            'types-requests==2.33.0.20260712',
            'types-setuptools==83.0.0.20260724',
            'typing==3.7.4.3',
            'typing_extensions==4.16.0',
            'urllib3==2.7.0',
            'userpath==1.9.2',
            'sphinx',
            'sphinx_rtd_theme',
            'sphinx_autodoc_typehints',
            'sphinx_paramlinks',
            'aedev_base',
            'aedev_project_vars',
            'anybadge',
            'flake8',
            'mypy',
            'pylint',
            'pytest',
            'pytest-cov',
            'typing',
            'types-setuptools',
        ],
        'docs': [
            'sphinx',
            'sphinx_rtd_theme',
            'sphinx_autodoc_typehints',
            'sphinx_paramlinks',
            'aedev_base',
            'aedev_project_vars',
        ],
        'tests': [
            'anybadge',
            'flake8',
            'mypy',
            'pylint',
            'pytest',
            'pytest-cov',
            'typing',
            'types-setuptools',
        ],
    },
    'install_requires': [],
    'keywords': [
        'configuration',
        'development',
        'environment',
        'productivity',
    ],
    'license': 'GPL-3.0-or-later',
    'long_description': (pathlib.Path(__file__).parent / 'README.md').read_text(encoding='utf-8'),
    'long_description_content_type': 'text/markdown',
    'name': 'aedev_aedev',
    'package_data': {
        '': [
            'templates/SkpTyp-namespace-root_fSt-PutMar-README.md',
        ],
    },
    'packages': [
        'aedev.aedev',
        'aedev.aedev.templates',
    ],
    'project_urls': {
        'Bug Tracker': 'https://gitlab.com/aedev-group/aedev_aedev/-/issues',
        'Documentation': 'https://aedev.readthedocs.io/en/latest/_autosummary/aedev.aedev.html',
        'Repository': 'https://gitlab.com/aedev-group/aedev_aedev',
        'Source': 'https://aedev.readthedocs.io/en/latest/_modules/aedev/aedev.html',
    },
    'python_requires': '>=3.12',
    'url': 'https://gitlab.com/aedev-group/aedev_aedev',
    'version': '0.3.34',
    'zip_safe': False,
}

if __name__ == "__main__":
    setuptools.setup(**setup_kwargs)
    ...
